FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
VOLUME /root/.m2
CMD ["/bin/bash"]

# ------------------------------------- COMANDOS ----------------------------------------------------------
# Construir la imagemn
#> docker build -f Dockerfile-maven -t maven-cli .

# Se queda de forma interactiva esperando comandos maven: mvn clean package, mvn verify..., exit para salir
#> docker run -it --name mvn-cli -v ${PWD}:/app -v maven-cache:/root/.m2 maven-cli

# Si ya esta creado el contenedor pero detenido, se quiere arrancar y quedarse en consola
# docker start -i mvn-cli

# si el contenedor esta arrancado, conectarse a consola
# docker exec -it mvn-cli /bin/bash


# OTROS COMANDOS

#> ejecuta el comando y se baja todas las dependencias, ya que no se reutilizan el volumen de dependencias
#> docker run --rm -v ${PWD}:/app maven-cli mvn -f /app clean

