services:
  maven-cli:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: mvn-cli
    working_dir: /app
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    command: ["/bin/bash"]
    stdin_open: true
    tty: true

volumes:
  maven_cache:
    name: "maven-cache"
